### ISSUE TITLE
Making connection before being sure whether the driver has loaded

### ISSUE THREAD

**Issue by codingnerd1007** [hemant61201/Motadata_Learning#5]
https://github.com/hemant61201/Motadata_Learning/blob/97dacc33f01f791afc63658f8fc1488a6322d19d/JQuery/src/main/java/Person_Info.java#L75

what will happen if the driver has failed to load, you are still going to make a connection, is it a right approach?

I understand that it won't cause an issue as it is in trywithresource, I just want know your perspective

**Comment by hemant61201** [comment]
if driver failed to load it throws ClassNotFound exception because it with try blocks and I put that in try with resource because after the execution of all the task my connection, preparestatement both are close automatically.
